version: "3.9"

services:
  app:
    build: app/
    env_file:
      - .env.dev
    restart: unless-stopped
    command: "python main.py --env dev"
    healthcheck:
      test:
        ["CMD-SHELL", "wget localhost:8000/api/health -q -O - > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - tinycdn_dev

  nginx:
    image: nginx:1.23.4-alpine

    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/ssl
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tinycdn_dev

networks:
  tinycdn_dev:
