version: "3.9"

services:
  app:
    build: app/
    env_file:
      - .env

  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
